//! Generator for the tutorial dungeon (PLAN.md 11.8 Phase 7, COMPANIONS.md 12): an entry
//! hall, a passage with two turns (the PVS must cut), the gate room with its two sentinels,
//! a short stair and the Warden's hall. Rooms are rectangles cut out of rock on a 64-unit
//! grid; everything that is not a room is solid.

use crate::mapgen::{Map, fix_worldspawn_closure};

/// The grid the rooms are cut on.
const CELL: f32 = 64.0;
/// The whole dungeon, in cells.
const X0: i32 = -32;
const X1: i32 = 32;
const Y0: i32 = -16;
const Y1: i32 = 16;
const WALL: f32 = 16.0;
/// Top of the rock; the Warden's hall is this high above the lower floor.
const TOP: f32 = 384.0;
/// The Warden's hall stands this much higher than the rest.
pub const HALL_FLOOR: f32 = 64.0;

/// A room: a rectangle of cells with its ceiling height above the lower floor.
struct Room {
    x0: i32,
    y0: i32,
    x1: i32,
    y1: i32,
    ceiling: f32,
}

const fn room(x0: i32, y0: i32, x1: i32, y1: i32, ceiling: f32) -> Room {
    Room {
        x0,
        y0,
        x1,
        y1,
        ceiling,
    }
}

/// Entry hall, three passage legs, gate room, stair, the Warden's hall (in cells of 64 u).
const ROOMS: [Room; 7] = [
    room(-31, -7, -21, 7, 288.0),
    room(-21, -1, -14, 2, 160.0),
    room(-17, 2, -14, 10, 160.0),
    room(-14, 7, -9, 10, 160.0),
    room(-9, 2, 3, 14, 288.0),
    room(3, 7, 9, 10, 224.0),
    room(9, -3, 31, 14, TOP),
];

fn open(x: i32, y: i32) -> bool {
    ROOMS
        .iter()
        .any(|r| (r.x0..r.x1).contains(&x) && (r.y0..r.y1).contains(&y))
}

/// Posts of the creatures: `(creature, encounter, x, y, z, yaw)`.
pub const POSTS: [(&str, &str, f32, f32, f32, i32); 3] = [
    ("sentinel", "gate", 96.0, 480.0, 25.0, 180),
    ("sentinel", "gate", 96.0, 608.0, 25.0, 180),
    ("warden", "warden", 1600.0, 352.0, HALL_FLOOR + 25.0, 180),
];

/// The dungeon as `.map` text.
pub fn generate() -> String {
    let mut m = Map::new();
    m.out.push_str(
        "// gamengine dungeon: the tutorial. Generated by `gm-tools map gen-dungeon`;\n\
         // hand edits are fine, regenerate only to change the layout wholesale.\n",
    );
    m.out.push_str(
        "{\n\"classname\" \"worldspawn\"\n\"message\" \"dungeon\"\n\"wad\" \"base.wad\"\n\"light\" \"11\"\n\
         \"_minlight_color\" \"150 160 200\"\n\"_dirt\" \"1\"\n\"_bounce\" \"1\"\n",
    );
    let (ex0, ex1) = (X0 as f32 * CELL, X1 as f32 * CELL);
    let (ey0, ey1) = (Y0 as f32 * CELL, Y1 as f32 * CELL);

    // The shell: floor, ceiling and four walls round the whole extent.
    m.boxb(
        [ex0 - WALL, ey0 - WALL, -WALL],
        [ex1 + WALL, ey1 + WALL, 0.0],
        "dungeon_floor",
        "dungeon_floor",
        "dungeon_floor",
    );
    m.boxb(
        [ex0 - WALL, ey0 - WALL, TOP],
        [ex1 + WALL, ey1 + WALL, TOP + WALL],
        "dungeon_wall",
        "dungeon_wall",
        "dungeon_wall",
    );
    for (x0, y0, x1, y1) in [
        (ex0 - WALL, ey0 - WALL, ex0, ey1 + WALL),
        (ex1, ey0 - WALL, ex1 + WALL, ey1 + WALL),
        (ex0, ey0 - WALL, ex1, ey0),
        (ex0, ey1, ex1, ey1 + WALL),
    ] {
        m.boxb(
            [x0, y0, 0.0],
            [x1, y1, TOP],
            "dungeon_wall",
            "dungeon_wall",
            "dungeon_wall",
        );
    }

    // Rock: every cell that is not a room, merged into rows and the rows into slabs.
    let mut runs: Vec<(i32, i32, i32, i32)> = Vec::new(); // x0, x1, y0, y1
    for y in Y0..Y1 {
        let mut x = X0;
        while x < X1 {
            if open(x, y) {
                x += 1;
                continue;
            }
            let start = x;
            while x < X1 && !open(x, y) {
                x += 1;
            }
            match runs
                .iter_mut()
                .find(|r| r.0 == start && r.1 == x && r.3 == y)
            {
                Some(r) => r.3 = y + 1,
                None => runs.push((start, x, y, y + 1)),
            }
        }
    }
    for (x0, x1, y0, y1) in runs {
        m.boxb(
            [x0 as f32 * CELL, y0 as f32 * CELL, 0.0],
            [x1 as f32 * CELL, y1 as f32 * CELL, TOP],
            "dungeon_wall",
            "dungeon_wall",
            "dungeon_wall",
        );
    }
    // Ceilings lower than the rock's top.
    for r in ROOMS.iter().filter(|r| r.ceiling < TOP) {
        m.boxb(
            [r.x0 as f32 * CELL, r.y0 as f32 * CELL, r.ceiling],
            [r.x1 as f32 * CELL, r.y1 as f32 * CELL, TOP],
            "dungeon_wall",
            "dungeon_wall",
            "trim_dark",
        );
    }

    // The stair: four steps of 16 up to the hall's floor, which is a slab on the lower one.
    for i in 0..4 {
        let x = 240.0 + 48.0 * i as f32;
        m.boxb(
            [x, 448.0, 16.0 * i as f32],
            [576.0, 640.0, 16.0 * (i + 1) as f32],
            "trim_dark",
            "dungeon_floor",
            "trim_dark",
        );
    }
    m.boxb(
        [576.0, -192.0, 0.0],
        [1984.0, 896.0, HALL_FLOOR],
        "trim_dark",
        "dungeon_floor",
        "trim_dark",
    );
    // The hall: four pillars and the dais the Warden stands before.
    for (x, y) in [
        (960.0, 64.0),
        (960.0, 576.0),
        (1344.0, 64.0),
        (1344.0, 576.0),
    ] {
        m.boxb(
            [x, y, HALL_FLOOR],
            [x + 64.0, y + 64.0, TOP],
            "rune_stone",
            "rune_stone",
            "rune_stone",
        );
    }
    m.boxb(
        [1728.0, 160.0, HALL_FLOOR],
        [1984.0, 544.0, HALL_FLOOR + 16.0],
        "trim_dark",
        "rune_stone",
        "trim_dark",
    );
    // The gate room: two blocks of waist-high cover between its doors.
    for y in [320.0, 640.0] {
        m.boxb(
            [-256.0, y, 0.0],
            [-192.0, y + 64.0, 44.0],
            "trim_dark",
            "metal_panel",
            "trim_dark",
        );
    }

    // Torches: warm in the low rooms, cold in the hall, a red glow on the dais.
    let warm = [255, 170, 90];
    for (x, y, z, light) in [
        (-1960.0, -400.0, 170.0, 330),
        (-1960.0, 400.0, 170.0, 330),
        (-1380.0, -400.0, 170.0, 290),
        (-1380.0, 400.0, 170.0, 290),
        (-1664.0, 0.0, 250.0, 260),
        (-1150.0, 32.0, 120.0, 250),
        (-992.0, 384.0, 120.0, 250),
        (-736.0, 544.0, 120.0, 250),
        (-540.0, 170.0, 170.0, 300),
        (-540.0, 860.0, 170.0, 300),
        (160.0, 170.0, 170.0, 300),
        (160.0, 860.0, 170.0, 300),
        (-192.0, 512.0, 250.0, 290),
        (384.0, 544.0, 170.0, 250),
    ] {
        m.light(x, y, z, light, warm);
    }
    let cold = [150, 190, 255];
    for (x, y) in [
        (800.0, 0.0),
        (800.0, 700.0),
        (1180.0, 352.0),
        (1560.0, 0.0),
        (1560.0, 700.0),
        (640.0, 352.0),
    ] {
        m.light(x, y, 300.0, 360, cold);
    }
    m.light(1856.0, 352.0, 150.0, 400, [255, 90, 50]);

    // Arrivals in the entry hall, facing the passage.
    for iy in 0..3 {
        for ix in 0..3 {
            m.spawn(
                -1856.0 + ix as f32 * 96.0,
                -96.0 + iy as f32 * 96.0,
                40.0,
                0,
                0,
            );
        }
    }
    m.entity(&[
        ("classname", "info_player_start".into()),
        ("origin", "-1900 0 40".into()),
        ("angle", "0".into()),
    ]);
    for (creature, encounter, x, y, z, yaw) in POSTS {
        m.entity(&[
            ("classname", "gm_creature".into()),
            ("origin", format!("{x} {y} {z}")),
            ("angle", yaw.to_string()),
            ("creature", creature.into()),
            ("encounter", encounter.into()),
        ]);
    }
    m.out.push_str("}\n");
    fix_worldspawn_closure(m.out)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_dungeon_has_its_rooms_its_posts_and_balanced_blocks() {
        let text = generate();
        assert_eq!(text.matches("{\n").count(), text.matches("}\n").count());
        assert_eq!(text.matches("\"gm_creature\"").count(), 3);
        assert_eq!(text.matches("\"creature\" \"sentinel\"").count(), 2);
        assert_eq!(text.matches("\"creature\" \"warden\"").count(), 1);
        assert_eq!(text.matches("\"gm_spawn\"").count(), 9);
        assert_eq!(text.matches("\"info_player_start\"").count(), 1);
        let ws = text.find("\"classname\" \"worldspawn\"").unwrap();
        let first = text.find("\"classname\" \"light\"").unwrap();
        assert!(ws < first);
        assert_eq!(text, generate(), "the generator is deterministic");
    }

    #[test]
    fn the_rooms_connect_in_a_chain_and_every_post_and_spawn_is_in_one() {
        // Each room shares an edge of at least three cells (a doorway) with the next.
        for pair in ROOMS.windows(2) {
            let (a, b) = (&pair[0], &pair[1]);
            let overlap = |a0: i32, a1: i32, b0: i32, b1: i32| a1.min(b1) - a0.max(b0);
            let touch_x = (a.x1 == b.x0 || b.x1 == a.x0) && overlap(a.y0, a.y1, b.y0, b.y1) >= 3;
            let touch_y = (a.y1 == b.y0 || b.y1 == a.y0) && overlap(a.x0, a.x1, b.x0, b.x1) >= 3;
            assert!(touch_x || touch_y, "rooms do not connect");
        }
        let cell = |v: f32| (v / CELL).floor() as i32;
        for (_, _, x, y, _, _) in POSTS {
            assert!(open(cell(x), cell(y)), "a post is in rock: {x} {y}");
        }
        assert!(open(cell(-1900.0), cell(0.0)));
        // Nothing but the first and the last room touches the outside of the grid.
        for r in &ROOMS {
            assert!(r.x0 > X0 && r.x1 < X1 && r.y0 > Y0 && r.y1 < Y1);
        }
    }
}
