//! Generator for the town map (PLAN.md 11.8 Phase 6): a cobbled square under an open sky,
//! half-timbered houses around it, four gated streets, a well, a town board and the market:
//! a grid of stall tiles (ECONOMY.md 7). One open space on purpose: everyone in the square
//! sees everyone else, which is the worst case the avatar budget is measured in.

use crate::mapgen::{Map, fix_worldspawn_closure};

/// Half extents of the square.
const HALF_X: f32 = 1024.0;
const HALF_Y: f32 = 768.0;
/// Depth of the ring of houses around it.
const RING: f32 = 256.0;
const WALL: f32 = 16.0;
const SKY: f32 = 704.0;
/// Half width of a street.
const STREET: f32 = 160.0;

/// The market: `COLS × ROWS` tiles of `TILE` units, `PITCH` apart, the first tile's corner at
/// `MARKET`. `gm_stall_grid` carries the same numbers to the zone.
pub const COLS: u32 = 6;
pub const ROWS: u32 = 5;
pub const TILE: f32 = 128.0;
pub const PITCH: f32 = 160.0;
const MARKET: [f32; 2] = [48.0, -384.0];

/// A house: a half-timbered box with a tiled roof leaning towards the square.
/// `side` 0 north, 1 south, 2 east, 3 west; `a..b` along the wall.
fn house(m: &mut Map, side: u8, a: f32, b: f32, height: f32, timber: bool) {
    let wall = if timber {
        "timber_wall"
    } else {
        "plaster_wall"
    };
    let rise = 96.0;
    let eave = 24.0;
    match side {
        0 | 1 => {
            let s = if side == 0 { 1.0 } else { -1.0 };
            let (front, back) = (s * HALF_Y, s * (HALF_Y + RING));
            let (y0, y1) = if front < back {
                (front, back)
            } else {
                (back, front)
            };
            m.boxb(
                [a, y0, 0.0],
                [b, y1, height],
                wall,
                "trim_dark",
                "trim_dark",
            );
            // A stone plinth so the walls do not start at the cobbles.
            m.boxb(
                [a, if s > 0.0 { y0 - 4.0 } else { y1 }, 0.0],
                [b, if s > 0.0 { y0 } else { y1 + 4.0 }, 24.0],
                "floor_stone",
                "floor_stone",
                "floor_stone",
            );
            m.ramp_y(
                front - s * eave,
                back,
                a - 8.0,
                b + 8.0,
                height + 16.0,
                height + 16.0 + rise,
                "roof_tile",
            );
        }
        _ => {
            let s = if side == 2 { 1.0 } else { -1.0 };
            let (front, back) = (s * HALF_X, s * (HALF_X + RING));
            let (x0, x1) = if front < back {
                (front, back)
            } else {
                (back, front)
            };
            m.boxb(
                [x0, a, 0.0],
                [x1, b, height],
                wall,
                "trim_dark",
                "trim_dark",
            );
            m.boxb(
                [if s > 0.0 { x0 - 4.0 } else { x1 }, a, 0.0],
                [if s > 0.0 { x0 } else { x1 + 4.0 }, b, 24.0],
                "floor_stone",
                "floor_stone",
                "floor_stone",
            );
            m.ramp_x(
                front - s * eave,
                back,
                a - 8.0,
                b + 8.0,
                height + 16.0,
                height + 16.0 + rise,
                "roof_tile",
            );
        }
    }
}

/// Houses along one side between `from` and `to`, leaving the street in the middle open.
fn row(m: &mut Map, side: u8, from: f32, to: f32, seed: usize) {
    let widths = [320.0f32, 256.0, 288.0, 224.0];
    let heights = [224.0f32, 176.0, 256.0, 208.0, 192.0];
    let mut at = from;
    let mut i = seed;
    while at < to - 1.0 {
        let mut w = widths[i % widths.len()];
        // Stop at the street, and do not leave a sliver at the corner.
        let limit = if at < -STREET { -STREET } else { to };
        if at + w > limit - 96.0 {
            w = limit - at;
        }
        house(m, side, at, at + w, heights[i % heights.len()], i % 3 != 1);
        at += w;
        if (at - (-STREET)).abs() < 1.0 {
            at = STREET;
        }
        i += 1;
    }
}

/// The town as `.map` text.
pub fn generate() -> String {
    let mut m = Map::new();
    m.out.push_str(
        "// gamengine town: the market square. Generated by `gm-tools map gen-town`;\n\
         // hand edits are fine, regenerate only to change the layout wholesale.\n",
    );
    m.out.push_str(
        "{\n\"classname\" \"worldspawn\"\n\"message\" \"town\"\n\"wad\" \"base.wad\"\n\"light\" \"18\"\n\
         \"_minlight_color\" \"170 185 220\"\n\"_sunlight\" \"230\"\n\"_sunlight_mangle\" \"38 -52 0\"\n\
         \"_sunlight_color\" \"255 242 214\"\n\"_sunlight2\" \"70\"\n\"_sunlight2_color\" \"170 195 255\"\n\
         \"_dirt\" \"1\"\n\"_bounce\" \"1\"\n",
    );

    // The shell: the ground, and sky on every side and above. The houses stand inside it.
    let (ox, oy) = (HALF_X + RING, HALF_Y + RING);
    m.boxb(
        [-ox - WALL, -oy - WALL, -WALL],
        [ox + WALL, oy + WALL, 0.0],
        "cobble",
        "cobble",
        "cobble",
    );
    m.boxb(
        [-ox - WALL, -oy - WALL, SKY],
        [ox + WALL, oy + WALL, SKY + WALL],
        "sky_day",
        "sky_day",
        "sky_day",
    );
    m.boxb(
        [-ox - WALL, -oy - WALL, 0.0],
        [-ox, oy + WALL, SKY],
        "sky_day",
        "sky_day",
        "sky_day",
    );
    m.boxb(
        [ox, -oy - WALL, 0.0],
        [ox + WALL, oy + WALL, SKY],
        "sky_day",
        "sky_day",
        "sky_day",
    );
    m.boxb(
        [-ox, -oy - WALL, 0.0],
        [ox, -oy, SKY],
        "sky_day",
        "sky_day",
        "sky_day",
    );
    m.boxb(
        [-ox, oy, 0.0],
        [ox, oy + WALL, SKY],
        "sky_day",
        "sky_day",
        "sky_day",
    );

    // Houses on all four sides; the corners belong to the north and south rows.
    row(&mut m, 0, -ox, ox, 0);
    row(&mut m, 1, -ox, ox, 2);
    row(&mut m, 2, -HALF_Y, HALF_Y, 1);
    row(&mut m, 3, -HALF_Y, HALF_Y, 3);

    // A gate closes each street at the town wall.
    for (x0, y0, x1, y1) in [
        (-STREET, oy - 24.0, STREET, oy),
        (-STREET, -oy, STREET, -oy + 24.0),
        (ox - 24.0, -STREET, ox, STREET),
        (-ox, -STREET, -ox + 24.0, STREET),
    ] {
        m.boxb(
            [x0, y0, 0.0],
            [x1, y1, 208.0],
            "ramp_wood",
            "trim_dark",
            "trim_dark",
        );
        // The arch over it.
        m.boxb(
            [x0, y0, 208.0],
            [x1, y1, 256.0],
            "wall_brick",
            "floor_stone",
            "wall_brick",
        );
    }

    // The well, west of the middle: a low stone ring.
    let (wx, wy, r, t) = (-352.0f32, 64.0f32, 56.0f32, 12.0f32);
    for (x0, y0, x1, y1) in [
        (wx - r, wy - r, wx + r, wy - r + t),
        (wx - r, wy + r - t, wx + r, wy + r),
        (wx - r, wy - r + t, wx - r + t, wy + r - t),
        (wx + r - t, wy - r + t, wx + r, wy + r - t),
    ] {
        m.boxb(
            [x0, y0, 0.0],
            [x1, y1, 36.0],
            "floor_stone",
            "floor_stone",
            "floor_stone",
        );
    }
    m.boxb(
        [wx - r + t, wy - r + t, 0.0],
        [wx + r - t, wy + r - t, 6.0],
        "trim_dark",
        "metal_panel",
        "trim_dark",
    );
    // Its roof on two posts.
    for px in [wx - r + 2.0, wx + r - 10.0] {
        m.boxb(
            [px, wy - 4.0, 36.0],
            [px + 8.0, wy + 4.0, 120.0],
            "ramp_wood",
            "ramp_wood",
            "ramp_wood",
        );
    }
    m.boxb(
        [wx - r - 8.0, wy - 28.0, 120.0],
        [wx + r + 8.0, wy + 28.0, 128.0],
        "roof_tile",
        "roof_tile",
        "ramp_wood",
    );

    // The town board, by the market: two posts and the board between them.
    let (bx, by) = (-64.0f32, -560.0f32);
    for px in [bx - 56.0, bx + 48.0] {
        m.boxb(
            [px, by - 4.0, 0.0],
            [px + 8.0, by + 4.0, 104.0],
            "ramp_wood",
            "ramp_wood",
            "ramp_wood",
        );
    }
    m.boxb(
        [bx - 48.0, by - 3.0, 32.0],
        [bx + 48.0, by + 3.0, 96.0],
        "ramp_wood",
        "ramp_wood",
        "ramp_wood",
    );

    // The market: one marked flagstone per stall tile.
    for row in 0..ROWS {
        for col in 0..COLS {
            m.tile(
                [
                    MARKET[0] + col as f32 * PITCH,
                    MARKET[1] + row as f32 * PITCH,
                ],
                TILE,
                0.0,
                1.0,
                "trim_dark",
                "market_tile",
            );
        }
    }

    // A few lamps under the eaves: the sun does the rest.
    for (x, y) in [
        (-960.0f32, 700.0f32),
        (960.0, 700.0),
        (-960.0, -700.0),
        (960.0, -700.0),
    ] {
        m.light(x, y, 150.0, 200, [255, 190, 120]);
    }
    m.light(wx, wy, 100.0, 120, [255, 220, 170]);

    m.entity(&[
        ("classname", "gm_stall_grid".into()),
        // The centre of tile (0, 0), on the ground.
        (
            "origin",
            format!("{} {} 0", MARKET[0] + TILE / 2.0, MARKET[1] + TILE / 2.0),
        ),
        ("cols", COLS.to_string()),
        ("rows", ROWS.to_string()),
        ("pitch", PITCH.to_string()),
        ("tile", TILE.to_string()),
        // Stall keepers face west, towards the open half of the square.
        ("angle", "180".into()),
    ]);

    // Arrivals: a grid over the open western half, clear of the well.
    for iy in 0..11 {
        for ix in 0..12 {
            let (x, y) = (-960.0 + ix as f32 * 80.0, -700.0 + iy as f32 * 140.0);
            if (x - wx).abs() < r + 40.0 && (y - wy).abs() < r + 40.0 {
                continue;
            }
            m.spawn(x, y, 40.0, 0, 0);
        }
    }
    // The start of the offline client and of the benchmarks: the south-west corner, looking
    // across the square.
    m.entity(&[
        ("classname", "info_player_start".into()),
        ("origin", "-940 -660 40".into()),
        ("angle", "32".into()),
    ]);
    m.out.push_str("}\n");
    fix_worldspawn_closure(m.out)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_town_has_its_market_its_spawns_and_balanced_blocks() {
        let text = generate();
        assert_eq!(text.matches("{\n").count(), text.matches("}\n").count());
        assert_eq!(text.matches("market_tile").count(), (COLS * ROWS) as usize);
        assert_eq!(text.matches("\"gm_stall_grid\"").count(), 1);
        assert!(text.matches("\"gm_spawn\"").count() >= 120);
        assert_eq!(text.matches("\"info_player_start\"").count(), 1);
        assert!(text.contains("\"_sunlight\" \"230\""));
        // Exactly one worldspawn block, closed before the first entity.
        let ws = text.find("\"classname\" \"worldspawn\"").unwrap();
        let first = text.find("\"classname\" \"light\"").unwrap();
        assert!(ws < first);
        assert_eq!(text, generate(), "the generator is deterministic");
    }
}
